### ISSUE TITLE
unable to register for the site

### ISSUE THREAD

**Issue by FrankBohac** [adaptlearning/adapt_framework#665]
I am trying to sign up for the Adapt Community, but am unable to do so. I have tried twice with no results. In both cases I am supposed to receive an email which will allow me to confirm my email address and in both cases the email has not been received. I am now stuck, since I have no other email addresses to try. At this point I cant log in, cant continue the process to create an account and cant request a resend of the confirmation email.

**Comment by brian-learningpool** [comment]
@svenlaux can you look into this?

**Comment by svenlaux** [comment]
Will look into today.

**Comment by taylortom** [comment]
Probably an obvious question, but have you checked your junk mail folder? Could be a spam filter catching them.

**Comment by FrankBohac** [comment]
Yes, I checked in both cases: no email…

**Comment by taylortom** [comment]
Dang. Are you using a work e-mail address? We've had issues with server-based junk filter issues before now too, whereby the mail's quarantined or something before it gets to you.

**Comment by FrankBohac** [comment]
I tried using my work email address first, then my aol address second. Both times I received no email…

**Comment by FrankBohac** [comment]
Seems like you need a way to allow the person to start the process over (or request a resend of the confirmation email). Right  now I am hung up and cant go any further. Without being able to register for the site, I cant access the forums, which is what I am really trying to do, since I am having problems installing the Adapt package and need help…

**Comment by dancgray** [comment]
I had a similar problem, but for changing email address on my forum account. I had to get our email cloud hosts to whitelist these email/domains  hosting@kineo.com & noreply@community.adaptlearning.org.

**Comment by FrankBohac** [comment]
I checked the held mail area of our email server: there were no emails delivered from the registration process (which makes sense since I also tried the process from my aol email account with no results). The emails in this thread have been delivered with no problems…

 

Still stuck…

**Comment by FrankBohac** [comment]
Still looking for help….

**Comment by moloko** [comment]
someone with the right level of access will need to have a look at the server logs to determine why the email is not getting out

**Comment by moloko** [comment]
in the meantime, an admin could manually enrol @FrankBohac

**Comment by ghopuk** [comment]
Hi I'm having the same issue, I've tried my own hosted email address and my Hotmail. Could an admin also manually enrol me, cheers.

**Comment by FrankBohac** [comment]
Still need help….

**Comment by ghopuk** [comment]
@FrankBohac I managed to get access using a Gmail address

**Comment by FrankBohac** [comment]
It looks like you have more than one bug in the registration process. I tried to register again using a brand new gmail account (based on the feedback that I just received from you). Still no luck (I didn't receive the confirmation email from your end again). I have now tried to register using three different email accounts on three different email servers. It seems pretty clear that there is a bug at your end that is causing the email to not be sent out.

Also: when I tried to define my username it said 'frankbohac' was already used. However, I have never completed the registration process for that username, so I shouldn't have received the error. Then I tried again with 'frankbohac1' as the user name and received the error again (username already in use). Clearly this is a bug in your code, since I had never used this name before. Then I tried again using 'frankbohac11' as the user name and the process completed (but no email received).

The funny part of all this is that I am trying to register for the site so I can get help with the product install process which isn't working for me either. Can we get someone to finish off my registration by hand so I can get on with the 'real' problem I am having (this issue has now been open for 5 days which seems pretty excessive for such an apparently simple problem).

**Comment by FrankBohac** [comment]
Please: delete username frankbohac1 and frankbohac11. I would like to complete the registration for username frankbohac using the email address: bohac@bconserv.com

thanks

**Comment by taylortom** [comment]
Hi Frank, @svenlaux should have manually confirmed your account now, and we've opened a ticket with the support team to look into removing your other accounts. 

If you have any more issues, you can try posting on our gitter.im stream:
https://gitter.im/adaptlearning/general_chat
https://gitter.im/adaptlearning/adapt_framework

**Comment by FrankBohac** [comment]
No luck. I cant log in (I am still getting ‘invalid login’).

 

I tried to request my password, but of course I received no email.

**Comment by FrankBohac** [comment]
Did someone at your end try logging in as me to verify that everything was working correctly?

**Comment by taylortom** [comment]
Sorry to hear Sven's quick fix hasn't worked. I'm not sure whether anyone tried logging in to your account - I'm assuming not as they'd need to change your password.

The core issue is still in the hands of the community site hosts at the moment, I will report back here when I hear anything. In the meantime, feel free to ask your framework questions on gitter.

**Comment by taylortom** [comment]
**UPDATE**: The fix has been applied, but it may take several hours to take effect. The support engineers are testing the email notifications with the new settings now, and will update me when anything changes.

**Comment by brian-learningpool** [comment]
Email notifications are working again for me. :+1:

**Comment by FrankBohac** [comment]
Brian,

 

Its bad form to close a ticket before the person who opened it has verified the fix…

**Comment by FrankBohac** [comment]
Im still unable to log in. Obviously them email notification process doesn’t help me a this point, since I am well out of email address and can’t start the process over:

 

-           Has someone fixed my login id? Have they tested their fix? What is my correct logind/password?

-          Has someone deleted the incorrect registration attempts?

 

Please confirm that the requests that I have sent in have been made and tested.

 

So far I have to say that I am not very impressed with the software at your end nor the professionalism of the ‘support’. This doesn’t speak too well for Adapt so far…

**Comment by svenlaux** [comment]
Hi Frank,

I'm very sorry you have had a bad experience trying to register and log into the community site.

Your note allowed us to identify an issue with the mail server, which was fixed a while back. I'm not 100% sure what happened since then but I am glad to see that you have finally been able to log into the community site on 3rd August.

I hope that any further experience with Adapt is more positive.

Best regards,
Sven

**Comment by FrankBohac** [comment]
Hi,

 

Thanks for the update. Unfortunately I am still unable to install the product. I have had a ticket open for this problem for 20 days and haven’t had any input back for almost 2 weeks….

 

 

Frank
