### ISSUE TITLE
adaptModel::setupChildListeners listening to ALL child types

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#695]
This function should presumably set up listeners on its own children? At the moment each page model listens to changes on ALL article models, each article listens to changes on ALL block models etc.

**Comment by danielghost** [comment]
This was addressed in our fork a while ago, but I guess it didn't make its way back into adaptlearning during the v2 amends:
https://github.com/cgkineo/adapt-framework-kineoFork/blob/master/js/adapt-framework-kineoFork.js#L101-L109

**Comment by moloko** [comment]
is this still relevant?

**Comment by chris-steele** [comment]
Yeah, still the same issue in v2. The handlers for the change events all check the actual children (using getChildren), but this still seems like it should be fixed even if just for code readability. I'm not aware of it ever causing issues, but it would boost performance if nothing else. Happy to leave as is though.
